//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteUrSpend
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryIncome
    {
        public int idCategoryInc { get; set; }
        public string CategoryIncome1 { get; set; }
        public string DescriptionCategory { get; set; }
    }
}
