//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteUrSpend
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentBalance
    {
        public int IdBalance { get; set; }
        public Nullable<float> CurrentbalanceCash { get; set; }
        public Nullable<float> CurrentBalanceCard { get; set; }
    }
}
