//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WriteUrSpend
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryBuy
    {
        public int idOperation { get; set; }
        public float SumBuy { get; set; }
        public string NameCategory { get; set; }
        public System.DateTime DateBuy { get; set; }
        public string NameProduct { get; set; }
        public bool IsBuyMadeCard { get; set; }
    }
}
